# Generated by Django 4.2.19 on 2025-03-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
